# MidNite Solar Classic MODBUS Register Map
# Source: classic_register_map_Rev-C5-December-8-2013.pdf
# Format: { register: (R/W, Name, Conversion, Notes) }
# For multi-register entries, each register number is listed separately.

CLASSIC_REGISTERS = {
    4101: ("R",   "UNIT_ID",                          "[4101]MSB = PCB revision, [4101]LSB = Unit Type",                                              "PCB revision 0-255. Unit Type = voltage category. See Table 4101-1."),
    4102: ("R",   "UNIT_SW_DATE_RO",                  "Year = [4102]",                                                                                "Software Build date (year part)."),
    4103: ("R",   "UNIT_SW_DATE_RO",                  "Month = [4103]MSB, Day = [4103]LSB",                                                           "Software Build date (month/day part)."),
    4104: ("R",   "InfoFlagsBits3",                    "WhizBangJrCrcGood Bit 0x0001",                                                                 "Information Flags word 3."),
    4105: ("—",   "RESERVED",                          "",                                                                                             ""),
    4106: ("R",   "UNIT_MAC_AddressI",                 "[4108]MSB:[4108]LSB:[4107]MSB:[4107]LSB:[4106]MSB:[4106]LSB",                                  "Unit Ethernet MAC address (low bytes)."),
    4107: ("R",   "UNIT_MAC_AddressI",                 "[4108]MSB:[4108]LSB:[4107]MSB:[4107]LSB:[4106]MSB:[4106]LSB",                                  "Unit Ethernet MAC address (mid bytes)."),
    4108: ("R",   "UNIT_MAC_AddressI",                 "[4108]MSB:[4108]LSB:[4107]MSB:[4107]LSB:[4106]MSB:[4106]LSB",                                  "Unit Ethernet MAC address (high bytes)."),
    4109: ("R",   "WbJrAmpHourNET",                    "(([4110] << 16) + [4109]) Amp Hours",                                                          "Whizbang Jr. Net amp hours (temporary). Clone of 4369."),
    4110: ("R",   "WbJrAmpHourNET",                    "(([4110] << 16) + [4109]) Amp Hours",                                                          "Whizbang Jr. Net amp hours (temporary). Clone of 4369."),
    4111: ("R",   "UNIT_Device_ID",                    "([4112] << 16) + [4111]",                                                                      "Device ID of the unit."),
    4112: ("R",   "UNIT_Device_ID",                    "([4112] << 16) + [4111]",                                                                      "Device ID of the unit."),
    4113: ("R",   "StatusRoll",                        "([4113]>>12) Count + ([4113] & 0x0fff) Value",                                                  "Various 12-bit values, changes once per second. Hi 4 bits = count."),
    4114: ("R",   "RestartTimerms",                    "[4114] Milliseconds",                                                                           "Time after which the Classic can wake up (countdown)."),
    4115: ("R",   "dispavgVbatt",                      "([4115] /10) Volts",                                                                            "Average Battery Voltage (1 sec)."),
    4116: ("R",   "dispavgVpv",                        "([4116] /10) Volts",                                                                            "Average PV terminal input Voltage (1 second average)."),
    4117: ("R",   "IbattDisplayS",                     "([4117] /10) Amps",                                                                             "Average Battery Current (1 sec)."),
    4118: ("R",   "kW--Hours",                         "([4118] /10) kWatt-Hours",                                                                      "Average Energy to the Battery. Reset once per day."),
    4119: ("R",   "Watts",                             "[4119] Watts",                                                                                  "Average Power to the Battery."),
    4120: ("R",   "ComboChargeStage",                  "Charge Stage = [4120]MSB, State = [4120]LSB",                                                   "See Table 4120-1 for battery charge state. See Table 4120-2."),
    4121: ("R",   "PvInputCurrent",                    "([4121] /10) Amps",                                                                             "Average PV terminal input Current (1 second average)."),
    4122: ("R",   "VocLastMeasured",                   "([4122] /10) Volts",                                                                            "Last measured open-circuit Voltage at the PV terminal input."),
    4123: ("R",   "HighestVinputLog (EE)",             "[4123] Voltage /10",                                                                            "Highest input voltage seen."),
    4124: ("R",   "MatchPointShadow",                  "[4124]",                                                                                        "Present wind power curve step being indexed (1..16)."),
    4125: ("R",   "AmpHours",                          "[4125] Amp Hours",                                                                              "Daily Amp Hours, reset at 23:59."),
    4126: ("R",   "Lifetime kW-Hours (EE)",            "(([4127] << 16) + [4126]) kWh",                                                                 "Lifetime Energy Generation."),
    4127: ("R",   "Lifetime kW-Hours (EE)",            "(([4127] << 16) + [4126]) kWh",                                                                 "Lifetime Energy Generation."),
    4128: ("R",   "LifetimeAmpHours (EE)",             "(([4129] << 16) + [4128]) Amp Hours",                                                           "Lifetime Amp-Hour Generation."),
    4129: ("R",   "LifetimeAmpHours (EE)",             "(([4129] << 16) + [4128]) Amp Hours",                                                           "Lifetime Amp-Hour Generation."),
    4130: ("R",   "InfoFlagsBits",                     "([4131] << 16) + [4130]",                                                                       "See Table 4130-1 (read as 32 bits or singly)."),
    4131: ("R",   "InfoFlagsBits2",                    "([4131] << 16) + [4130]",                                                                       "See Table 4130-1 (read as 32 bits or singly)."),
    4132: ("R",   "BATTtemperature",                   "([4132] /10) °C",                                                                               "Temperature at external Battery Temperature Sensor (if installed, else 25°C)."),
    4133: ("R",   "FETtemperature",                    "([4133] /10) °C",                                                                               "Temperature of Power FETs."),
    4134: ("R",   "PCBTemperature",                    "([4134] /10) °C",                                                                               "Temperature of the Classic Control (top) PCB."),
    4135: ("R",   "NiteMinutesNoPwr",                  "[4135] minutes",                                                                                "Counts up when no power. Resets to 0 when there is power."),
    4136: ("R/W", "MinuteLogIntervalSec (EE)",         "[4136] seconds",                                                                                "Minimum 60 seconds recent history data logging interval."),
    4137: ("R/W", "modbus_port_register (EE)",         "[4137] 0 to 65,535",                                                                            "Default = 502."),
    4138: ("R",   "FloatTimeTodaySeconds",             "[4138] seconds",                                                                                "Seconds batteries have spent in float today. Reset at 23:59."),
    4139: ("R/W", "AbsorbTime",                        "[4139] seconds",                                                                                "Absorb Time Up/Down Counter. Goes to Float when it reaches 0."),
    4140: ("—",   "RESERVED",                          "",                                                                                             "May show Ibatt in older firmware."),
    4141: ("R",   "PWM_ReadOnly",                      "[4141] (0 to 1023)",                                                                            "Duty Cycle command of PWM signal (NOT Percent)."),
    4142: ("R",   "Reason_For_Reset",                  "",                                                                                              "Reason the Classic reset (WDT, etc). See Table 4142-1."),
    4143: ("R/W", "Equalize Time",                     "[4143] Seconds",                                                                                "Battery Stage Equalize Down Counter. Time remaining in Equalize Stage. EQ Done when it reaches 0."),
    4144: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE (was used for Solar Tracking debug)."),
    4145: ("R/W", "MppWLast",                          "[4145]",                                                                                        "Internal watts ref. for Solar Re-Tracking (~10% of last MPP W). If written, will be overwritten next Solar sweep."),
    4146: ("R/W", "USBcommMODE (EE)",                  "[4146] USB Function #",                                                                         "See Table 4146-1."),
    4147: ("R/W", "NoDoubleClickTimer",                "[4147] Seconds",                                                                                "Internal forced time space between manual MPPT sweeps."),
    4148: ("R/W", "Battery output Current Limit (EE)", "([4148] /10) Amps",                                                                             "Battery Current Limit Amps (e.g. 23.4 A = 234)."),
    4149: ("R/W", "Absorb Set Point Voltage (EE)",     "([4149] /10) Volts",                                                                            "Battery Absorb Stage Set point Voltage (e.g. 28.3V = 283)."),
    4150: ("R/W", "Float Voltage Set Point (EE)",      "([4150] /10) Volts",                                                                            "Battery Float Stage Set Point Voltage."),
    4151: ("R/W", "Equalize Voltage Set Point (EE)",   "([4151] /10) Volts",                                                                            "Battery Equalize Stage Set Point Voltage."),
    4152: ("R",   "Sliding Current Limit",             "[4152] Amps",                                                                                   "Sliding Current Limit (changes with V/Temp etc.)."),
    4153: ("R/W", "Minimum Absorb Time (EE)",          "[4153] seconds",                                                                                "Minimum Absorb time when VariMax is used. Otherwise equals 0. (Normally unused now.)"),
    4154: ("R/W", "Absorb Time (EE)",                  "[4154] seconds",                                                                                "Set Point time for Batteries to be in the Absorb Stage."),
    4155: ("R/W", "Maximum Battery Temperature Compensation Voltage (EE)", "([4155] /10) Volts",                                                        "Highest Charge Voltage is limited to this value when using battery temp sensor."),
    4156: ("R/W", "Minimum Battery Temperature Compensation Voltage (EE)", "([4155] /10) Volts",                                                        "Lowest Charge Voltage is limited to this value when using battery temp sensor."),
    4157: ("R/W", "Battery Temp Comp Value for each 2V cell (EE)",        "-([4157] /10) mV/degree C/cell (0.5 mV steps) 0 to 10 mV per 2V cell",       "Absolute value of the Temperature Compensation Value in mV/°C/2V cell."),
    4158: ("R/W", "General Purpose 16 bit word (EE)",  "",                                                                                              "Stored & retrieved with other EEprom (was Battery Type)."),
    4159: ("R/W", "EqualizeReTryDays (EE)",            "[4159]",                                                                                        "Number of days for auto EQ to retry until giving up."),
    4160: ("W",   "Force Flag Bits",                   "([4161] << 16) + [4160]",                                                                       "See Table 4160-1."),
    4161: ("W",   "Force Flag Bits",                   "([4161] << 16) + [4160]",                                                                       "See Table 4160-1."),
    4162: ("R/W", "Equalize Time (EE)",                "[4162] Seconds",                                                                                "Initialize Time for Batteries to remain in Equalize stage."),
    4163: ("R/W", "Equalize Interval Days (EE)",       "[4163] Days",                                                                                   "Number of days between Equalize Stages (Auto EQ)."),
    4164: ("R/W", "Mppt Mode / Solar, Wind, etc. (EE)","[4164] (bit 0 = On/Off)",                                                                       "Classic functional Mode. See Table 4164-1."),
    4165: ("R/W", "Aux 1 and 2 Function (EE)",         "[4165] Combined Aux 1&2 Functions + On/Off",                                                     "See Table 4165-1 and 4165-2."),
    4166: ("R/W", "Aux1VoltsLoAbs (EE)",               "([4166] /10) Volts",                                                                            "Aux 1 Low Absolute Threshold Voltage."),
    4167: ("R/W", "Aux1DelayT (EE)",                   "[4167] Milliseconds",                                                                           "Aux 1 Delay time before Asserting."),
    4168: ("R/W", "Aux1HoldT (EE)",                    "[4168] Milliseconds",                                                                           "Aux 1 Hold time before De-asserting."),
    4169: ("R/W", "Aux2PwmVwidth (EE)",                "([4169] /10) Volts",                                                                            "Voltage range over which PWM operates for Aux 2. 0,1,2,3,4 or 5 volts."),
    4170: ("—",   "RESERVED",                          "",                                                                                             ""),
    4171: ("—",   "RESERVED",                          "",                                                                                             ""),
    4172: ("R/W", "Aux1VoltsHiAbs (EE)",               "([4172] /10) Volts",                                                                            "Aux 1 High Absolute Threshold Voltage."),
    4173: ("R/W", "Aux2VoltsHiAbs (EE)",               "([4173] /10) Volts",                                                                            "Aux 2 High Absolute Threshold Voltage."),
    4174: ("R/W", "Aux1VoltsLoRel (EE)",               "([4174] /10) Volts",                                                                            "Aux 1 Waste-Not Relative Lower Voltage Threshold (Charge Stage Relative V)."),
    4175: ("R/W", "Aux1VoltsHiRel (EE)",               "([4175] /10) Volts",                                                                            "Aux 1 Waste-Not Relative Upper Voltage Threshold (Charge Stage Relative V)."),
    4176: ("R/W", "Aux2VoltsLoRel (EE)",               "([4176] /10) Volts",                                                                            "Aux 2 Waste-Not Relative Lower Voltage Threshold (Charge Stage Relative V)."),
    4177: ("R/W", "Aux2VoltsHiRel (EE)",               "([4177] /10) Volts",                                                                            "Aux 2 Waste-Not Relative Upper Voltage Threshold (Charge Stage Relative V)."),
    4178: ("R/W", "Aux1VoltsLoPv (EE)",                "([4178] /10) Volts",                                                                            "Aux 1 Lower PV Absolute Threshold Voltage."),
    4179: ("R/W", "Aux1VoltsHiPv (EE)",                "([4179] /10) Volts",                                                                            "Aux 1 High PV Absolute Threshold Voltage."),
    4180: ("R/W", "VariMax (EE)",                      "[4180] LSB = Amps, [4180] MSB = Vabsorb-Vrelative /10",                                         "Default = 101 amps."),
    4181: ("R/W", "Aux2VoltsHiPv (EE)",                "([4181] /10) Volts",                                                                            "Aux 2 High PV Absolute Threshold Voltage."),
    4182: ("R/W", "EnableFlags3 (EE)",                 "[4182] binary",                                                                                 "See Table 4182-1."),
    4183: ("R/W", "ArcFaultSenstvty (EE)",             "Time=[4183], Sense=[4183], Mode=[4183]<<16",                                                    "Arc Fault Protection sensitivity response adjustments. Requires Classic reset."),
    4184: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4185: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4186: ("R/W", "EnableFlags2 (EE)",                 "[4186] binary",                                                                                 "See Table 4186-1."),
    4187: ("R/W", "EnableFlagsBits (EE)",              "[4187] binary",                                                                                 "See Table 4187-1."),
    4188: ("R/W", "RESERVED FACTORY CALIBRATION",      "",                                                                                             "DO NOT WRITE."),
    4189: ("R/W", "Vbatt_Offset (EE)",                 "([4189] /10)",                                                                                  "Battery Voltage Offset Tweak (Range Limited, Signed)."),
    4190: ("R/W", "Vpv_Offset (EE)",                   "([4190] /10)",                                                                                  "Input Voltage Offset Tweak (Range Limited, Signed)."),
    4191: ("R",   "VpvTargetRd",                       "([4191] /10) Volts",                                                                            "Input Target (V regulation) Voltage (Usually Vmpp)."),
    4192: ("R/W", "VpvTargetWr (EE)",                  "([4192] /10) Volts",                                                                            "Vpv Target command (VpvTargetCmdEn)."),
    4193: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4194: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4195: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4196: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4197: ("R/W", "SweepIntervalSecs (EE)",            "[4197] Seconds",                                                                                "Legacy P&O, Hydro, Solar, U-Set Sweep Interval in seconds. Forcing Sweep resets timer."),
    4198: ("R/W", "MinSwpVoltage (EE)",                "([4198] /10)",                                                                                  "Minimum input voltage for Hydro MPPT mode sweep."),
    4199: ("R/W", "MaxInputCurrent (EE)",              "([4199] /10) amps (dflt = 99A)",                                                                "Maximum input current limit."),
    4200: ("R/W", "SweepDepth (EE)",                   "[4200] watts %",                                                                                "Maximum % Legacy/Hydro mode will sweep as percent of present Mpp wattage."),
    4201: ("R/W", "NegativeCurrent Adj. (EE)",         "",                                                                                              "Factory calibration. Do not change unless instructed."),
    4202: ("R",   "ClipperCmdVolts",                   "([4202] /10) Volts",                                                                            "Aux clipper reference varies w/stage and headroom."),
    4203: ("R/W", "WindNumberOfPoles (EE)",            "[4203] poles",                                                                                  "Number of turbine alternator poles for RPM Calc. (unused)."),
    4204: ("R/W", "MppPercentVoc (EE)",                "[4204] 00 to 100 %",                                                                            "% of Voc for U-Set mode."),
    4205: ("R/W", "WindTableToUse (EE)",               "[4205]",                                                                                        "FUTURE power curve select."),
    4206: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4207: ("R/W", "LEDmode (EE)",                      "[4207]",                                                                                        "See Table 4207-1."),
    4208: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4209: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4210: ("R/W", "ID name (EE)",                      "[4210]LSB || [4210]MSB || [4211]LSB || [4211]MSB || [4212]LSB || [4212]MSB || [4213]LSB || [4213]MSB", "Unit Name, 8 characters max, ASCII. End with 0 if less than 8 chars."),
    4211: ("R/W", "ID name (EE)",                      "",                                                                                              "Unit Name continuation (chars 3-4)."),
    4212: ("R/W", "ID name (EE)",                      "",                                                                                              "Unit Name continuation (chars 5-6)."),
    4213: ("R/W", "ID name (EE)",                      "",                                                                                              "Unit Name continuation (chars 7-8)."),
    4214: ("R",   "CTIME0",                            "([4215] << 16) + [4214] (possibly atomic op)",                                                  "Consolidated Time Registers. See Table 4214-1."),
    4215: ("R",   "CTIME0",                            "([4215] << 16) + [4214] (possibly atomic op)",                                                  "Consolidated Time Registers. See Table 4214-1."),
    4216: ("R",   "CTIME1",                            "([4217] << 16) + [4216] (possibly atomic op)",                                                  "Consolidated Time Registers. See Table 4216-1."),
    4217: ("R",   "CTIME1",                            "([4217] << 16) + [4216] (possibly atomic op)",                                                  "Consolidated Time Registers. See Table 4216-1."),
    4218: ("R",   "CTIME2",                            "[4218]",                                                                                        "Consolidated Time Registers. See Table 4218-1."),
    4219: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4220: ("R/W", "RemoteMenuMode",                    "[4220]",                                                                                        "Present Remote Menu sent from MNGP."),
    4221: ("W",   "RemoteButtons",                     "[4221]",                                                                                        "MNGP Buttons Pressed. See Table 4221-1."),
    4222: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4223: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4224: ("R/W", "PreVoc (do not write)",             "([4224] /10) Volts",                                                                            "Input Voc before Relay."),
    4225: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4226: ("R/W", "Aux2_A2D_D2A",                     "[4226] 10 bits, right justified",                                                               "Aux 2 A/D and D/A value."),
    4227: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4228: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4229: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4230: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4231: ("R",   "VocRD",                             "([4231] /10) Volts",                                                                            "Last VOC reading."),
    4232: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4233: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4234: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4235: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4236: ("R/W", "AbsorbTime (duplicate)",            "[4236] seconds",                                                                                "Absorb Time Counter."),
    4237: ("R/W", "AntiClickSenstvty (EE)",            "[4237]",                                                                                        "Best Left Alone (varies)."),
    4238: ("R/W", "SiestaTime",                        "[4238] seconds",                                                                                "Sleep timer (5 minutes max)."),
    4239: ("R",   "SiestaAbortVocAdj",                 "([4239] /10) Volts",                                                                            "Volts above last Voc reading to abort Siesta."),
    4240: ("R",   "flagsRD",                           "([4241] << 16) + [4240]",                                                                       "Internal Flags. See Table 4240-1."),
    4241: ("R",   "flagsRD",                           "([4241] << 16) + [4240]",                                                                       "Internal Flags. See Table 4240-1."),
    4242: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4243: ("—",   "RESERVED",                          "",                                                                                             ""),
    4244: ("R",   "VbattRegSetPTmpComp",               "([4244] /10) Volts",                                                                            "Temperature compensated battery regulation target voltage."),
    4245: ("R/W", "VbattNominal (EE)",                 "[4245] 12 * 1 thru 10 (120 Max for 250 KS)",                                                    "Nominal Battery bank voltage (i.e. 12V, 24V, etc)."),
    4246: ("R/W", "EndingAmps (EE)",                   "([4246] /10) Amps (Default = 0.0 amps)",                                                        "Goes to Float below this Batt current if Temp Comp'd Absorb voltage is held."),
    4247: ("R/W", "EndingSoc (EE)",                    "",                                                                                              "SOC to end Absorb. Future SOC use."),
    4248: ("—",   "EndAmpSocMBaddress",                "",                                                                                              "Modbus address of Ibatt. Future SOC use."),
    4249: ("R/W", "RebulkVolts (EE)",                  "([4249] /10) Volts",                                                                            "Rebulks if battery drops below this for > 90 seconds."),
    4250: ("R",   "BattMonVolts",                      "",                                                                                              "Battery Monitor Volts. Future SOC use."),
    4251: ("R",   "BattMonSOC",                        "",                                                                                              "Battery Monitor SOC. Future SOC use."),
    4252: ("R",   "DaysBtwnBulkAbs (EE)",              "",                                                                                              "Days between Bulk/Absorb cycles. Default = 0. If 1, will Re-bulk every other day, etc."),
    4253: ("R",   "BattMonAHefficiency (EE)",          "",                                                                                              "Battery Monitor A-Hour efficiency. Future SOC use."),
    4254: ("R/W", "DayLogCombCatIndex",                "[4254] (Category << 10) + (-Day Offset & 0x3ff)",                                               "See Table 4254-1 for Daily logs."),
    4255: ("R",   "LogValueRead",                      "[4255]",                                                                                        "Requested single logging Cat. data point appears here."),
    4256: ("R/W", "MinLogCombCatIndex",                "[4256] (Category << 10) + (-Data Point Offset & 0x3ff)",                                        "See Table 4256-1 for Recent/Hourly/Minutely logs."),
    4257: ("R/W", "RebulkTimerSec",                    "[4257] seconds",                                                                                "Set Point Rebulk interval timer seconds. Cleared if Vbatt >= Rebulk V in Float MPPT."),
    4258: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4259: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4260: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4261: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4262: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4263: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4264: ("R/W", "Voc_Qualify_Timer_1ms",             "(([4265] << 16) + [4264]) msec",                                                                "Timer (msec) qualifying time till turn on valid (not very useful)."),
    4265: ("R/W", "Voc_Qualify_Timer_1ms",             "(([4265] << 16) + [4264]) msec",                                                                "Timer (msec) qualifying time till turn on valid (not very useful)."),
    4266: ("R",   "IpvMinus",                          "[4266] amps (peak A). 1 count = 0.1 amp",                                                       "Raw PV negative current from A/D converter."),
    4267: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4268: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4269: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4270: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4271: ("R",   "RestartTimerms",                    "[4271] Milliseconds",                                                                           "Count Down Time until Wake Allowed at < 500 ms."),
    4272: ("R",   "Ibatt",                             "([4272] /10) Amps (peak A)",                                                                    "Battery Current, Unfiltered."),
    4273: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4274: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4275: ("R",   "ReasonForResting",                  "[4275] Reason number",                                                                          "Reason Classic went to Rest. See Table 4275-1."),
    4276: ("R",   "Output Vbatt",                      "([4376] /10) Volts (peak V)",                                                                   "Battery Voltage Unfiltered."),
    4277: ("R",   "Input Vpv",                         "([4377] /10) Volts (peak V)",                                                                   "PV Voltage Unfiltered."),
    4278: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4279: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4280: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4281: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4282: ("R",   "PkHoldVpvStamp",                    "",                                                                                              "Internal variable for Solar MPPT."),
    4283: ("R",   "VpvTargetRd (temporary)",           "[4283] /10",                                                                                    "Vpv input voltage target (MPP voltage)."),
    4284: ("R",   "SwpDeepTimeoutSec",                 "",                                                                                              "Internal variable for Solar MPPT."),
    4285: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4286: ("R/W", "LowWatts (EE)",                     "[4286]",                                                                                        "Classic will go to Resting when watts are less than this for > 90 seconds in NON-wind modes unless Insomnia is set."),
    4287: ("R/W", "WindLowWatts (dflt=50) (EE)",       "",                                                                                              "Below this watts for wind, looks for power window."),
    4288: ("R/W", "WindWindowWattsRef (EE)",           "",                                                                                              "If wind power wiggles above this, keep running."),
    4289: ("R",   "WindowWattsRO",                     "",                                                                                              "Delta watts below WindLowWatts that power is wiggling."),
    4290: ("R/W", "WindTimeOutRef (EE)",               "",                                                                                              "If power is low for this many seconds, go to Resting (default 90)."),
    4291: ("R/W", "WindTimeOut2Ref (EE)",              "",                                                                                              "Seconds, Reference default = 1800 (1/2 hour)."),
    4292: ("R/W", "WindTimeOut",                       "",                                                                                              "Seconds, Timer. If > WindTimeOutRef, goes to Resting."),
    4293: ("R/W", "WindTimeOut2",                      "",                                                                                              "Seconds, Timer. If > WindTimeOut2Ref, goes to Resting."),
    4294: ("R",   "MinVpvTurnOn",                      "",                                                                                              "Minimum input voltage required to come out of Resting."),
    4295: ("R",   "VpvB4TurnOff",                      "",                                                                                              "Internal reference of Vpv when going to Resting."),
    4296: ("R/W", "HydroSwpAmps10Time6",               "",                                                                                              "Internal reference for hydro sweep speed."),
    4297: ("R/W", "EndingAmpsTimerSec",                "",                                                                                              "Seconds, Timer for Ending Amps. 60 seconds reference."),
    4298: ("R/W", "PkAmpsOverLimitHi (EE)",            "",                                                                                              "Factory calibration. Leave as is."),
    4299: ("R/W", "PkAmpsOverLimitLo (EE)",            "",                                                                                              "Factory calibration. Leave as is."),
    4300: ("R/W", "FactoryVbattOffset (EE)",           "",                                                                                              "Factory V battery offset calibration. Normally, leave alone."),
    4301: ("R/W", "WindPowerTableV +0 (EE)",           "(WindPowerTableV(stp1) << 8) + WindPowerTableV(stp0)",                                          "Wind power curve voltage steps 0 and 1."),
    4302: ("R/W", "WindPowerTableV +1 (EE)",           "(WindPowerTableV(stp3) << 8) + WindPowerTableV(stp2)",                                          "Wind power curve voltage steps 2 and 3."),
    4303: ("R/W", "WindPowerTableV +2 (EE)",           "(WindPowerTableV(stp5) << 8) + WindPowerTableV(stp4)",                                          "Wind power curve voltage steps 4 and 5."),
    4304: ("R/W", "WindPowerTableV +3 (EE)",           "(WindPowerTableV(stp7) << 8) + WindPowerTableV(stp6)",                                          "Wind power curve voltage steps 6 and 7."),
    4305: ("R/W", "WindPowerTableV +4 (EE)",           "(WindPowerTableV(stp9) << 8) + WindPowerTableV(stp8)",                                          "Wind power curve voltage steps 8 and 9."),
    4306: ("R/W", "WindPowerTableV +5 (EE)",           "(WindPowerTableV(stp11) << 8) + WindPowerTableV(stp10)",                                        "Wind power curve voltage steps 10 and 11."),
    4307: ("R/W", "WindPowerTableV +6 (EE)",           "(WindPowerTableV(stp13) << 8) + WindPowerTableV(stp12)",                                        "Wind power curve voltage steps 12 and 13."),
    4308: ("R/W", "WindPowerTableV +7 (EE)",           "(WindPowerTableV(stp15) << 8) + WindPowerTableV(stp14)",                                        "Wind power curve voltage steps 14 and 15."),
    4309: ("R/W", "WindPowerTableI +0 (EE)",           "(WindPowerTableI(stp1) << 8) + WindPowerTableI(stp0)",                                          "Wind power curve current steps 0 and 1."),
    4310: ("R/W", "WindPowerTableI +1 (EE)",           "(WindPowerTableI(stp3) << 8) + WindPowerTableI(stp2)",                                          "Wind power curve current steps 2 and 3."),
    4311: ("R/W", "WindPowerTableI +2 (EE)",           "(WindPowerTableI(stp5) << 8) + WindPowerTableI(stp4)",                                          "Wind power curve current steps 4 and 5."),
    4312: ("R/W", "WindPowerTableI +3 (EE)",           "(WindPowerTableI(stp7) << 8) + WindPowerTableI(stp6)",                                          "Wind power curve current steps 6 and 7."),
    4313: ("R/W", "WindPowerTableI +4 (EE)",           "(WindPowerTableI(stp9) << 8) + WindPowerTableI(stp8)",                                          "Wind power curve current steps 8 and 9."),
    4314: ("R/W", "WindPowerTableI +5 (EE)",           "(WindPowerTableI(stp11) << 8) + WindPowerTableI(stp10)",                                        "Wind power curve current steps 10 and 11."),
    4315: ("R/W", "WindPowerTableI +6 (EE)",           "(WindPowerTableI(stp13) << 8) + WindPowerTableI(stp12)",                                        "Wind power curve current steps 12 and 13."),
    4316: ("R/W", "WindPowerTableI +7 (EE)",           "(WindPowerTableI(stp15) << 8) + WindPowerTableI(stp14)",                                        "Wind power curve current steps 14 and 15."),
    4317: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4318: ("R/W", "PkAmpsOverTrip (EE)",               "",                                                                                              "Factory calibration. Leave as is."),
    4319: ("R",   "mngp_revision",                     "",                                                                                              "Preliminary. Also shows unit is connected."),
    4320: ("R",   "mnlp_revision",                     "",                                                                                              "Preliminary. Also shows unit is connected."),
    4321: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4322: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4323: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4324: ("—",   "RESERVED",                          "",                                                                                             "DO NOT WRITE."),
    4325: ("—",   "RESERVED",                          "",                                                                                             ""),
    4326: ("R/W", "ClassicModbusAddr (EE)",            "0 to 255",                                                                                      "Classic Modbus Addr. Default address = 10."),
    4327: ("R/W", "BatteryTempPassed",                 "",                                                                                              "Follow-Me temp sensor value."),
    4328: ("R",   "iFlagsRO Low",                      "",                                                                                              "Used for Follow-Me. Reflects neighboring units' charge stage for charge coordination. See Table 4328-1."),
    4329: ("R",   "iFlagsRO High",                     "",                                                                                              "Used for Follow-Me. Reflects neighboring units' charge stage for charge coordination. See Table 4328-1."),
    4330: ("R/W", "ModbusControl",                     "",                                                                                              "Follow Me."),
    4331: ("R/W", "ClassicFmePassedBits",              "",                                                                                              "Follow Me."),
    4332: ("R/W", "WindSynchA",                        "",                                                                                              "Wind power tracking amps. Follow Me."),
    4333: ("R/W", "WindSynchV",                        "",                                                                                              "Wind power tracking volts. Follow Me."),
    4334: ("R/W", "FollowMePassRef (EE)",              "",                                                                                              "Follow Me enabled if > 0. Classic ignores changes for FollowMePassRef times around the communications loop."),
    4335: ("—",   "RESERVED",                          "",                                                                                             ""),
    4336: ("—",   "RESERVED",                          "",                                                                                             ""),
    4337: ("—",   "RESERVED",                          "",                                                                                             ""),
    4338: ("—",   "RESERVED",                          "",                                                                                             ""),
    4339: ("—",   "RESERVED",                          "",                                                                                             ""),
    4340: ("—",   "RESERVED",                          "",                                                                                             ""),
    4341: ("R",   "DabtU32Debug01",                    "",                                                                                              "Data Abort info if Watch Dog reset occurs."),
    4342: ("R",   "DabtU32Debug02",                    "",                                                                                              "Data Abort info if Watch Dog reset occurs."),
    4343: ("R",   "DabtU32Debug03",                    "",                                                                                              "Data Abort info if Watch Dog reset occurs."),
    4344: ("R",   "DabtU32Debug04",                    "",                                                                                              "Data Abort info if Watch Dog reset occurs."),
    4345: ("—",   "RESERVED",                          "",                                                                                             ""),
    4346: ("—",   "RESERVED",                          "",                                                                                             ""),
    4347: ("—",   "RESERVED",                          "",                                                                                             ""),
    4348: ("—",   "RESERVED",                          "",                                                                                             ""),
    4349: ("—",   "RESERVED",                          "",                                                                                             ""),
    4350: ("—",   "RESERVED",                          "",                                                                                             ""),
    4351: ("—",   "RESERVED",                          "",                                                                                             ""),
    4352: ("R",   "CRC Network",                       "CRC 16",                                                                                        "Network code area CRC."),
    4353: ("R",   "CRC Application",                   "CRC 16",                                                                                        "Application code area CRC."),
    4354: ("R/W", "ClearLogsCat",                      "",                                                                                              "Clears various logging values. See Table 4354-1."),
    4355: ("R",   "ClearLogsCounter10ms",              "",                                                                                              "Timer for sending 2nd ClearLogsCat command before timeout."),
    4356: ("R/W", "User Variable 02",                  "",                                                                                              "General purpose user variable."),
    4357: ("R",   "WizBangRxBufferTempSh1",            "",                                                                                              "Raw Whizbang Junior buffer read 1."),
    4358: ("R",   "WizBangRxBufferTempSh2",            "",                                                                                              "Raw Whizbang Junior buffer read 2."),
    4359: ("R",   "WizBangRxBufferTempSh3",            "",                                                                                              "Raw Whizbang Junior buffer read 3."),
    4360: ("R",   "WizBangRxBufferTempSh4",            "",                                                                                              "Raw Whizbang Junior buffer read 4."),
    4361: ("R/W", "WbangJrCmdS (EE)",                  "",                                                                                              "Whizbang Junior Command. Default 0x35."),
    4362: ("R",   "WizBangJrRawCurrent",               "",                                                                                              "WB Jr. raw current (not scaled or rounded), signed A/D counts."),
    4363: ("R/W", "WbJrNumeratorSS (EE)",              "",                                                                                              "Whizbang Jr. gain adjustment. Default = 0 (signed) gain adjust +-32,767."),
    4364: ("—",   "Reserved",                          "",                                                                                             ""),
    4365: ("R",   "WbJrAmpHourPOSitive",               "(([4366] << 16) + [4365]) Amp Hours Pos. (unsigned)",                                           "Positive Whizbang Jr. amp hours."),
    4366: ("R",   "WbJrAmpHourPOSitive",               "(([4366] << 16) + [4365]) Amp Hours Pos. (unsigned)",                                           "Positive Whizbang Jr. amp hours."),
    4367: ("R",   "WbJrAmpHourNEGative",               "(([4368] << 16) + [4367]) Amp Hours Neg. (signed)",                                             "Negative Whizbang Jr. amp hours."),
    4368: ("R",   "WbJrAmpHourNEGative",               "(([4368] << 16) + [4367]) Amp Hours Neg. (signed)",                                             "Negative Whizbang Jr. amp hours."),
    4369: ("R",   "WbJrAmpHourNET",                    "(([4370] << 16) + [4369]) Amp Hours NET (signed)",                                              "Whizbang Jr. Net amp hours."),
    4370: ("R",   "WbJrAmpHourNET",                    "(([4370] << 16) + [4369]) Amp Hours NET (signed)",                                              "Whizbang Jr. Net amp hours."),
    4371: ("R",   "WzBangJrCurrent32Signed",           "",                                                                                              "Whizbang Jr. amps (scaled and rounded), signed +- 3,276.7 amps."),
    4372: ("R",   "WizBangJrRawCrcAndtemp",            "(Raw CRC << 8) | Temperature & 0xff + 50C",                                                     "WB Jr. CRC, Temperature in C -50 C."),
    4373: ("—",   "Reserved",                          "",                                                                                             ""),
}


if __name__ == "__main__":
    # Quick demo: print all readable registers with their name and conversion
    print(f"Total registers defined: {len(CLASSIC_REGISTERS)}\n")
    print(f"{'Register':<10} {'R/W':<5} {'Name':<50} {'Conversion'}")
    print("-" * 120)
    for reg, (rw, name, conv, notes) in sorted(CLASSIC_REGISTERS.items()):
        print(f"{reg:<10} {rw:<5} {name:<50} {conv}")
